### ISSUE TITLE
Installation fehlgeschlagen 

### ISSUE THREAD

**Issue by MaSven** [Dragowynd/ProxerHTML5#1]
Die installation durch diese URL https://github.com/Dragowynd/ProxerHTML5/raw/master/proxerhtml5.user.js klappt nicht es kommt folgende Fehlermeldung 

Skript konnte nicht analysiert werden: Ignoriere @match Regel http_://proxer.me/watch_ wegen: Error: @Treffer: Das muster konnte nicht geladen werden. 

Firefox version 36.04 for Opensuse 
Einfügen als benutzerskipt scheint auch nicht zu klappen. Proxer streams laden danach einfach nicht mehr.

**Comment by Darksider3** [comment]
Selbiges hier. Obwohl es nicht an der @matching Regel liegen sollte, weil ich auch bei einer Globalzulassung(@match *) den Player nicht zum laufen kriegte.
Fehlermeldung - auch, das selbe.

**Comment by jonbkei** [comment]
@Eiamnacken @Darksider3 ich schau mir das mal an, könnte daran liegen dass GM für firefox keinen \* parameter an gewissen stellen mag ^-^
