### ISSUE TITLE
Script funktioniert nicht in firefox

### ISSUE THREAD

**Issue by jonbkei** [Dragowynd/ProxerHTML5#2]
@Darksider3 @Eiamnacken

momentan liegt es daran, dass firefox mitten in der onload funktion der GM_xmlhttprequest einfach aufhört den codeblock weiter auszuführen.

**Comment by Darksider3** [comment]
Weil ich weder durch Firebug, noch durch die Firefox Debugging-Console etwas herausfinden konnte, habe ich nun Zeile für Zeile der onload() gecheckt, indem ich dahinter ein `console.log("after[BlockDescription]")` packte. Außerdem ist GM_log laut Greasepot deprecated. ;-) (Also auch aus dem Skript entfernt :smile:).

Das Problem liegt in der Zeile:

``` javascript
var s = toDOM(match.toString());
```

`match.toString()` gibt zurück:

``` javascript
<Script> function $$(elem){return document.getElementById(elem);} function player_start() {     $$('player_ads').style.display = 'none';     $$('player_img').style.display = 'none';     $$('player_code').style.visibility = 'visible';     if($$('np_vid')) $$('np_vid').Play();     return false; } </Script>
```

... schaut "irgendwie" falsch aus, weil Du im nächsten Schritt auf `s.src` zugreifst - was inexistent ist/sein sollte.
EDIT: Ist inexistent:

``` javascript
console.log(match.toString().src)
```

gibt "undefined" zurück.

**Comment by jonbkei** [comment]
@Darksider3 ich verstehe worauf du rauswillst, leider hast du die funktion der toDOM methode komplett ignoriert, diese wandelt das ganze nämlich in ein [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element) um. (In Chrome zumindest) haben diese dann falls der tag das src attribut besitzt auch ein src Attribut.
Du hast aber recht es ist nicht der standardisierte Weg um das abzufragen, ich werde es mal ändern.

**Comment by Darksider3** [comment]
Stimmt, ich hab's nicht so mit Javascript - geschweige denn Dojo(nur da konnte ich eine Doku zu toDOM() finden)! :laughing:
