### ISSUE TITLE
Volume is always maximum

### ISSUE THREAD

**Issue by Argard** [Dragowynd/ProxerHTML5#3]
Usually video players remember what volume was selected last time. The ProxerStream with this script doesn't. This wouldn't be very annoying if the ProxerStream wouldn't have maximum volume as standard selection and I have to change it at the start of each video. I think it would be better if the standard would be 50% volume. An other possibility is that it's a bug. I use Google Chrome and I'm not running other scripts. Anyway this script is still great, it was a very pleasant surprise that this exists.

Greetings Aargard

**Comment by jonbkei** [comment]
That's a problem with video.js itself, the bug has been reported at https://github.com/videojs/video.js/issues/2066 but hasn't been fixed yet.
